version: '3.8'

services:
  web:
    build:
      context: .
    container_name: laravel-apache
    ports:
      - "80:80"
    volumes:  
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "" 
      MYSQL_DATABASE: mercado  
      MYSQL_USER: root        
      MYSQL_PASSWORD: ""     
    ports:
      - "3307:3307"  
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  mysql-data:

networks:
  laravel_network:
    driver: bridge
