version: '3.8'

services:
  # Serviço da aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"  # Mapeia a porta 80 do container para a porta 8000 do host
    volumes:
      - .:/var/www/html  # Mapeia o diretório atual para /var/www/html no container
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mercado
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql
    networks:
      - laravel_network

  # Serviço do MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: mercado
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"  # Porta para acessar o MySQL do host
    volumes:
      - mysql_data:/var/lib/mysql  # Volume persistente para o MySQL
    networks:
      - laravel_network

volumes:
  mysql_data:  # Define o volume persistente para o MySQL

networks:
  laravel_network:  # Define uma rede compartilhada para os containers
    driver: bridge
